Task 6 implementation
ozonmp/edu-platform-api pull request #7
Opened 2021-11-23 16:01 UTC by vyacheslav-startsev

Сделал:

1. Имплементировать отправку событий в **kafka** топик

2. Имплементировать для сервиса `{domain-kw}-{subdomain}-facade` чтение данных из **kafka** топика в стандартный поток вывода

3. Имплементировать **update** операцию

4. Имплементировать сохранение прочтенных данных в базу 💎

5. Добавить поддержку работы с множеством брокеров 💎

2021-11-23 17:32 UTC, LiFeAiR requested changes

2021-11-23 17:32 UTC, LiFeAiR commented on internal/app/sender/event.go
> +	if platformEvent.Entity != nil {
`platformEvent` тоже может быть nil...

2021-11-23 17:32 UTC, LiFeAiR commented on internal/repo/repo.go
> +		return errors.Wrap(err, "repo.Update")
`repo.Update: runner.ExecContext`

2021-11-23 17:32 UTC, LiFeAiR commented on internal/repo/repo.go
> +		return errors.Wrap(err, "repo.Update")
`repo.Update: query.ToSql`

2021-11-23 17:32 UTC, LiFeAiR commented on internal/repo/repo.go
> +		return errors.Wrap(err, "repo.Update")
`repo.Update: res.RowsAffected`

2021-11-23 17:32 UTC, LiFeAiR commented on internal/service/service.go
> +			return err
`errors.Wrap(`

2021-11-24 03:55 UTC, vyacheslav-startsev commented on internal/app/sender/event.go
> +	if platformEvent.Entity != nil {
добавил проверку

2021-12-23 01:31 UTC, merged